name: Publish PyRs to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Build the PyO3 library
      run: maturin build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ pypi-AgEIcHlwaS5vcmcCJGM1N2UzYTkwLWY1NmMtNDA5OC1iOGE4LTA1Mjg2NDQxODQwZAACKlszLCJhZjExN2JmNi0wYjQwLTRlNzItYmY4Zi0xYmIyYTA2YjIxNGYiXQAABiAGNKwwybiAbCpA3qu1WnWbQOB6NYcAUMD0nrhhhPPcFA }}
